# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Instalar git para clonar el repositorio
RUN apt-get update && apt-get install -y git && apt-get clean

# Clonar el repositorio de Awesome Threat Intelligence
RUN git clone https://github.com/hslatman/awesome-threat-intelligence.git

# Cambiar al directorio del repositorio
WORKDIR /app/awesome-threat-intelligence

# Instalar dependencias necesarias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el archivo de la aplicación al contenedor
COPY awesome_ti_app.py .

# Exponer el puerto en el que la aplicación correrá
EXPOSE 8081

# Comando por defecto: ejecutar la aplicación Flask
CMD ["python", "awesome_ti_app.py"]
