# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo requirements.txt y las dependencias en el contenedor
COPY requirements.txt .

# Instalar las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos de la aplicación en el contenedor
COPY . .

# Exponer el puerto en el que la aplicación correrá, si aplica (puedes ajustar según sea necesario)
EXPOSE 8081

# Comando para ejecutar la aplicación
CMD ["python", "threatfox_app.py"]
